# baseURL = "localhost"
baseurl = "https://www.cryptopatrick.com/"
relativeURLs = true
title = "Seamless Global Nature"
copyright = "'I write to understand as much as to be understood.' —Elie Wiesel<br> (c) 2024 CryptoPatrick"
languageCode = "en-EN"
metaDataFormat = "yaml"
theme = "seamless"
pagerSize = 10
#paginate = 10
#pagination.path = "page"
path = "page"
#paginatePath = "page"
#canonifyurls = true

disqusShortname = "cryptopatrick"
enableEmoji = true
#discus short name ? "www--cryptopatrick--com"?

[permalinks]
    post = "/blog/:year/:month/:day/:slug/"
    code = "/:slug/"

#[taxonomies]
#    tag = "tags"
#    topic = "topics"

[author]
    name = "CryptoPatrick"
    email = "cryptopatrick@gmail.com"

[params]
author = "CryptoPatrick"
#googleAnalytics = ""
#sharingicons = true
keywords = ["keyword 1", "keyword 2", "keyword 3"]
profilePicture = "/profile.jpg"

#Optional syntax highlight starts here
# styles: https://github.com/alecthomas/chroma/tree/master/styles
# styles gallery: https://xyproto.github.io/splash/docs/
#[markup]
 [markup.highlight]
    #noClasses = false
    #style="abap"
    #style="monokailight"
    #style="algol"
    #style="tango"
    #style="autumn"
    style="arduino"
    #style="average"
    #style="base16-snazzy"
    #style="borland"
    #style="bw"
        #style="xcode"
   #style="github-light"
#   linenos=false
   #style="igor"
   #lineNumbersInTable=false
#   tabWidth=4
#Optional syntax highlight ends here.

# Select a syntax highight.
    # Check the static/css/highlight directory for options.
    #highlight = "nord"

[markup.goldmark.renderer]
unsafe= true  # allows html in markdown

[params.highlight]
#style = "github-light"
languages = ["rust", "python"]
customCSS = ["css/customcode.css"]

#[[params.social]]
#url = "https://x.com/cryptopatrick"
#fa_icon = "fa-twitter"

#[[params.social]]
#url = "https://github.com/cryptopatrick"
#fa_icon = "fa-github"

#[[params.social]]
#url = "https://crates.io/users/cryptopatrick"
#fa_icon = "fa-cubes"


#[[params.social]]
#url = "/index.xml"
#fa_icon = "fa-rss"

[[params.static_pages]]
#url = "/about/"
#tag = "About"

[[params.static_pages]]
#url = "/portfolio/"
#tag = "Portfolio"


#[[params.mermaid]]
#theme = "dark"
#align = "center"

#theme = "dark"
#theme = "default" - This is the default theme for all diagrams.
#theme = "neutral" - This theme is great for black and white documents that will be printed.
#theme = "dark" - This theme goes well with dark-colored elements or dark-mode.
#theme = "forest" - This theme contains shades of green.
#theme = "base" - This is the only th
#params:
#   mermaid:
#       theme: "dark"
#       align: "center"
